go_library(
    name = "installer",
    srcs = ["installer.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//common/go/backoff",
        "//common/go/helm",
        "//common/go/minikube",
        "//common/go/retry",
        "//third_party/go:logrus",
    ],
)
