remote_file(
    name = "helm",
    url = "https://get.helm.sh/helm-v3.6.2-linux-amd64.tar.gz",
    hashes = ["f3a4be96b8a3b61b14eec1a35072e1d6e695352e7a08751775abf77861a0bf54"],
    binary = True,
    extract = True,
    exported_files = ["linux-amd64/helm"],
)
