go_library(
    name = "k8s",
    srcs = ["k8s.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//third_party/go:go-k8s",
        "//third_party/go:k8s-api",
        "//third_party/go:k8s-apimachinery",
        "//third_party/go:logrus",
    ],
)
