go_library(
    name = "db",
    srcs = ["db.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//common/go/backoff",
        "//common/go/retry",
        "//third_party/go:flags",
        "//third_party/go:logrus",
        "//third_party/go:pq",
        "//third_party/go:sqlx",
    ],
)
