# TODO: Replace this with variables taken from hashicorp vault for rotating DB keys
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app: postgres
data:
  POSTGRES_DB: ZGI= # db
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # password
  POSTGRES_USER: YWRtaW4= # admin
