go_library(
    name = "steps",
    srcs = [
        "common.go",
        "helm.go",
        "k8s.go",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "//common/go/installer",
        "//third_party/go:logrus",
    ],
)
