go_binary(
    name = "deploy-vault",
    srcs = ["deploy_vault.go"],
    deps = [
        "//services/helm",
        "//services/minikube",
        "//third_party/go:flags",
        "//third_party/go:logrus",
        "//tools/helm",
    ],
)
